---
- name: Task 14 - Configuration Management
  hosts: webservers
  become: yes

  vars:
    packages:
      - curl
      - git
      - nginx

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Ensure nginx is started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a config file
      copy:
        content: |
          server {
              listen 8080;
              server_name localhost;
          }
        dest: /etc/nginx/conf.d/custom.conf
        mode: '0644'
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
